-- =============================================================================
-- DEPRECADO — No ejecutar. Dejaba INSERT solo para taller_1 y rompía admin.
-- Usar en su lugar: sql/nm_hub_tasks_assigned_admin.sql (fix completo RLS + admin).
-- =============================================================================
